### ISSUE TITLE
Adding Function call  state or log. 

### ISSUE THREAD

**Issue by Pierre-Mike** [wladiston/aibitat#15]
Could we add a function call log? 
- help with debugging 
- improve history chat.

**Comment by wladiston** [comment]
I'm doing some experiments with that. My initial plan is to let functions to set their own state so we could still interrupt and continue later when needed.

There's essentially some use cases where that may be needed:
- `web browsing`: same as gpt, browsing includes search on the internet, navigate back and forth webpages, search on page, summarize... and you might not want to restart everything if the last interaction of the function gets some internet connection issue. 
- `async jobs`: payments or other stuff where the results are not necessarily immediate or might require some user interaction.

**Comment by Pierre-Mike** [comment]
for future memory function as well.
