### ISSUE TITLE
Hardcoded gpt4 model?

### ISSUE THREAD

**Issue by erikfunkis** [wladiston/aibitat#7]
Even when trying the index.ts example with model set to 

`
new AIbitat({
  provider: "openai",
  model: "gpt-3.5-turbo",
})
`

I'm getting an error from OpenAI `error: 404 The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.` 

It seems to be the hardcoded `model: 'gpt-4' as const` in `aibitat.ts` 

Best regards

**Comment by wladiston** [comment]
Thanks @erikfunkis !
The fix was implemented and it is going to come in the next release.
As a workaround, you can define the configuration directly on the channel like this:

```ts
...
  .channel('management', ['mathematician', 'reviewer', 'client'], {
    model: 'gpt-3.5-turbo'
  })
```
